// nuxt-proj/components/Square.vue
<template>
  <div
    :style="{
      width: width + 'px',
      height: height + 'px',
      backgroundColor: color,
    }"
  ></div>
</template>

<script lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

export default {
  props: {
    width: {
      type: Number,
      required: true,
    },
    height: {
      type: Number,
      required: true,
    },
  },
  setup() {
    const color = ref("#FFFFFF");

    const changeColor = () => {
      color.value = getRandomColor();
    };

    onMounted(() => {
      const interval = setInterval(changeColor, getRandomInterval());

      onUnmounted(() => {
        clearInterval(interval);
      });
    });

    return {
      color,
    };
  },
};
</script>

// nextjs-proj/app/components/Square.tsx
"use client";

import { useEffect, useState } from "react";
import { getRandomColor, getRandomInterval } from "../../helpers";

interface SquareProps {
  width: number;
  height: number;
}

export const Square = ({ width, height }: SquareProps) => {
  const [color, setColor] = useState("#FFFFFF");

  useEffect(() => {
    const changeColor = () => {
      setColor(getRandomColor());
    };

    const interval = setInterval(changeColor, getRandomInterval());

    return () => clearInterval(interval);
  }, []);

  return <div style={{ width, height, backgroundColor: color }} />;
};
