// nextjs-proj/app/components/Square.tsx
"use client";

import { useEffect, useState } from "react";
import { getRandomColor, getRandomInterval } from "../../helpers";

interface SquareProps {
  width: number;
  height: number;
}

export const Square = ({ width, height }: SquareProps) => {
  const [color, setColor] = useState("#FFFFFF");

  useEffect(() => {
    const changeColor = () => {
      setColor(getRandomColor());
    };

    const interval = setInterval(changeColor, getRandomInterval());

    return () => clearInterval(interval);
  }, []);

  return <div style={{ width, height, backgroundColor: color }} />;
};

// svelte-proj/src/lib/Square.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { writable } from 'svelte/store';
  import { getRandomColor, getRandomInterval } from './../helpers'
  
  export let width: number;
  export let height: number;

  const color = writable("#FFFFFF");
  let interval: number;

  onMount(() => {
    const changeColor = () => {
      color.set(getRandomColor());
    };

    interval = setInterval(changeColor, getRandomInterval());
  });

  onDestroy(() => clearInterval(interval));
</script>

<div style="width: {width}px; height: {height}px; background-color: {$color}" />
