// svelte-proj/src/lib/Square.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { writable } from 'svelte/store';
  import { getRandomColor, getRandomInterval } from './../helpers'
  
  export let width: number;
  export let height: number;

  const color = writable("#FFFFFF");
  let interval: number;

  onMount(() => {
    const changeColor = () => {
      color.set(getRandomColor());
    };

    interval = setInterval(changeColor, getRandomInterval());
  });

  onDestroy(() => clearInterval(interval));
</script>

<div style="width: {width}px; height: {height}px; background-color: {$color}" />

// angular-proj/src/app/components/square/square.component.ts
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { getRandomColor, getRandomInterval } from '../../helpers';

@Component({
  selector: 'app-square',
  templateUrl: './square.component.html',
  styleUrls: ['./square.component.css'],
})
export class SquareComponent implements OnInit, OnDestroy {
  @Input() width: number | undefined;
  @Input() height: number | undefined;
  color: string = '#FFFFFF';
  private intervalId: any;

  private changeColor(): void {
    this.color = getRandomColor();
  }

  ngOnInit(): void {
    this.changeColor();
    this.intervalId = setInterval(() => {
      this.changeColor();
    }, getRandomInterval());
  }

  ngOnDestroy(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }
}

<div
  [ngStyle]="{
    'width.px': width,
    'height.px': height,
    'background-color': color
  }"
></div>
