// nextjs-proj/app/[number_squares]/page.tsx
"use client";
import { useEffect, useRef, useState } from "react";
import { Square } from "../components/Square";

export default function Page({
  params,
}: {
  params: { number_squares: number };
}) {
  const [numSquares, setNumSquares] = useState(Number(params.number_squares));
  const [renderTime, setRenderTime] = useState<number | null>(null);
  const [fps, setFPS] = useState<number>(0);
  const [windowSize, setWindowSize] = useState<{
    width: number;
    height: number;
  }>({ width: 0, height: 0 });
  const frameCount = useRef<number>(0);
  const lastTime = useRef<number>(performance.now());
  const animationFrameRef = useRef<number>();

  useEffect(() => {
    const handleResize = () => {
      setWindowSize({ width: window.innerWidth, height: window.innerHeight });
    };

    // Initial window size
    handleResize();

    // Add event listener for resize
    window.addEventListener("resize", handleResize);

    return () => {
      // Remove event listener on cleanup
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  const renderSquares = () => {
    if (windowSize.width === 0 || windowSize.height === 0) {
      // If window size is not available yet, return null or loading indicator
      return null;
    }

    const squareSize = Math.min(
      windowSize.width / numSquares,
      windowSize.height / numSquares,
    );

    const squares = [];
    for (let i = 0; i < numSquares; i++) {
      for (let j = 0; j < numSquares; j++) {
        squares.push(
          <Square key={`${i}-${j}`} width={squareSize} height={squareSize} />,
        );
      }
    }
    return squares;
  };

  useEffect(() => {
    const animate = () => {
      frameCount.current += 1;
      const currentTime = performance.now();
      const deltaTime = currentTime - lastTime.current;

      if (deltaTime >= 1000) {
        const currentFPS = (frameCount.current / deltaTime) * 1000;
        setFPS(parseFloat(currentFPS.toFixed(2)));
        frameCount.current = 0;
        lastTime.current = currentTime;
      }

      animationFrameRef.current = requestAnimationFrame(animate);
    };

    animationFrameRef.current = requestAnimationFrame(animate);

    return () => {
      if (animationFrameRef.current) {
        cancelAnimationFrame(animationFrameRef.current);
      }
    };
  }, []);

  const addSquares = () => {
    const startTime = performance.now();
    setNumSquares(numSquares + 100);
    setRenderTime(null); // Reset render time
    // Wait for the next render cycle to measure the time after squares are rendered
    requestAnimationFrame(() => {
      const endTime = performance.now();
      setRenderTime(endTime - startTime); // Calculate render time
    });
  };

  return (
    <main>
      <button onClick={addSquares}>Add Squares</button>

      <p>FPS: {fps}</p>
      <p>
        Render Time:{" "}
        {renderTime !== null ? `${renderTime.toFixed(2)}ms` : "N/A"}
      </p>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: `repeat(${numSquares}, 1fr)`,
          gridTemplateRows: `repeat(${numSquares}, 1fr)`,
          width: "100vw",
          height: "100vh",
        }}
      >
        {renderSquares()}
      </div>
    </main>
  );
}

// svelte-proj/src/routes/[number_squares]/+page.svelte
<script lang="ts">
  import Square from '$lib/Square.svelte';
  import { writable, get } from 'svelte/store';
  import { page } from '$app/stores';
  import { onMount } from 'svelte';

  const numSquares = writable<number>(Number($page.params.number_squares));
  const renderTime = writable<number | null>(null);
  const fps = writable<number>(0);
  let squares: any[] = [];

  let frameCount = 0;
  let lastTime = performance.now();
  let animationFrameRef: number;

  onMount(() => {
    numSquares.set(Number(get(page).params.number_squares));

    const updateSquares = () => {
      const num = get(numSquares);
      const squareWidth = window.innerWidth / num;
      const squareHeight = window.innerHeight / num;

      squares = [];
      for (let i = 0; i < num; i++) {
        for (let j = 0; j < num; j++) {
          squares.push({ id: `${i}-${j}`, width: squareWidth, height: squareHeight });
        }
      }
    };

    numSquares.subscribe(() => {
      updateSquares();
    });

    updateSquares(); // Initialize squares on mount
  });

  onMount(() => {
    const animate = () => {
      frameCount += 1;
      const currentTime = performance.now();
      const deltaTime = currentTime - lastTime;

      if (deltaTime >= 1000) {
        const currentFPS = (frameCount / deltaTime) * 1000;
        fps.set(parseFloat(currentFPS.toFixed(2)));
        frameCount = 0;
        lastTime = currentTime;
      }

      animationFrameRef = requestAnimationFrame(animate);
    };

    animationFrameRef = requestAnimationFrame(animate);

    return () => {
      if (animationFrameRef) {
        cancelAnimationFrame(animationFrameRef);
      }
    };
  });

  const addSquares = () => {
    const startTime = performance.now();
    numSquares.update(n => n + 100);
    renderTime.set(null); // Reset render time

    requestAnimationFrame(() => {
      const endTime = performance.now();
      renderTime.set(endTime - startTime); // Calculate render time
    });
  };
</script>

<main>
  <button on:click={addSquares}>Add Squares</button>

  <p>FPS: {$fps}</p>
  <p>
    Render Time: {#if $renderTime !== null}{$renderTime.toFixed(2)}ms{:else}N/A{/if}
  </p>
  <div
    style="
      display: grid;
      grid-template-columns: repeat({$numSquares}, 1fr);
      grid-template-rows: repeat({$numSquares}, 1fr);
      width: 100vw;
      height: 100vh;
    "
  >
  {#each squares as square}
    <Square width={square.width} height={square.height} />
  {/each}
  </div>
</main>
